
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import matplotlib.pyplot as plt


attack = ctrl.Antecedent(np.arange(-0.81, 0.81, 0.01), 'attack')
midfield = ctrl.Antecedent(np.arange(-0.9, 0.9, 0.01), 'midfield')
defense = ctrl.Antecedent(np.arange(-0.87, 0.87, 0.01), 'defense')
bench = ctrl.Antecedent(np.arange(-0.58, 0.58, 0.01), 'bench')
result = ctrl.Consequent(np.arange(-100, 100, 1), 'result')

attack['terrible'] = fuzz.trimf(attack.universe, [-0.84, -0.81, -0.41])
attack['bad'] = fuzz.trimf(attack.universe, [-0.84, -0.41, 0])
attack['okay'] = fuzz.trimf(attack.universe, [-0.41, 0, 0.41])
attack['good'] = fuzz.trimf(attack.universe, [0, 0.41, 0.84])
attack['excellent'] = fuzz.trimf(attack.universe, [0.41, 0.84, 0.84])

midfield['terrible'] = fuzz.trimf(midfield.universe, [-0.74, -0.74, -0.37])
midfield['bad'] = fuzz.trimf(midfield.universe, [-0.74, -0.37, 0])
midfield['okay'] = fuzz.trimf(midfield.universe, [-0.37, 0, 0.37])
midfield['good'] = fuzz.trimf(midfield.universe, [0, 0.37, 0.74])
midfield['excellent'] = fuzz.trimf(midfield.universe, [0.37, 0.74, 0.74])

defense['terrible'] = fuzz.trimf(defense.universe, [-0.83, -0.83, -0.41])
defense['bad'] = fuzz.trimf(defense.universe, [-0.83, -0.41, 0])
defense['okay'] = fuzz.trimf(defense.universe, [-0.41, 0, 0.41])
defense['good'] = fuzz.trimf(defense.universe, [0, 0.41, 0.83])
defense['excellent'] = fuzz.trimf(defense.universe, [0.41, 0.83, 0.83])

bench['terrible'] = fuzz.trimf(bench.universe, [-0.82, -0.82, -0.41])
bench['bad'] = fuzz.trimf(bench.universe, [-0.82, -0.41, 0])
bench['okay'] = fuzz.trimf(bench.universe, [-0.41, 0, 0.41])
bench['good'] = fuzz.trimf(bench.universe, [0, 0.41, 0.82])
bench['excellent'] = fuzz.trimf(bench.universe, [0.41, 0.82, 0.82])

result['extreme_disavantage'] = fuzz.trimf(result.universe, [-100, -100, -66])
result['big_disavantage'] = fuzz.trimf(result.universe, [-100, -66, -33])
result['disavantage'] = fuzz.trimf(result.universe, [-66, -33, 0])
result['even'] = fuzz.trimf(result.universe, [-33, 0, 33])
result['advantage'] = fuzz.trimf(result.universe, [0, 33, 66])
result['big_vantage'] = fuzz.trimf(result.universe, [33, 66, 100])
result['extreme_vantage'] = fuzz.trimf(result.universe, [66, 100, 100])


rule1 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['terrible'] & bench['terrible'], result['extreme_disavantage'])
rule2 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['terrible'] & bench['bad'], result['extreme_disavantage'])
rule3 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['terrible'] & bench['okay'], result['extreme_disavantage'])
rule4 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['terrible'] & bench['good'], result['big_disavantage'])
rule5 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['terrible'] & bench['excellent'], result['big_disavantage'])
rule6 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['bad'] & bench['terrible'], result['extreme_disavantage'])
rule7 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['bad'] & bench['bad'], result['extreme_disavantage'])
rule8 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['bad'] & bench['okay'], result['big_disavantage'])
rule9 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['bad'] & bench['good'], result['big_disavantage'])
rule10 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['bad'] & bench['excellent'], result['big_disavantage'])
rule11 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['okay'] & bench['terrible'], result['extreme_disavantage'])
rule12 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['okay'] & bench['bad'], result['big_disavantage'])
rule13 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['okay'] & bench['okay'], result['big_disavantage'])
rule14 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['okay'] & bench['good'], result['big_disavantage'])
rule15 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['okay'] & bench['excellent'], result['disavantage'])
rule16 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['good'] & bench['terrible'], result['big_disavantage'])
rule17 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['good'] & bench['bad'], result['big_disavantage'])
rule18 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['good'] & bench['okay'], result['big_disavantage'])
rule19 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['good'] & bench['good'], result['disavantage'])
rule20 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['good'] & bench['excellent'], result['disavantage'])
rule21 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['excellent'] & bench['terrible'], result['big_disavantage'])
rule22 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['excellent'] & bench['bad'], result['big_disavantage'])
rule23 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['excellent'] & bench['okay'], result['disavantage'])
rule24 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['excellent'] & bench['good'], result['disavantage'])
rule25 = ctrl.Rule(attack['terrible'] & midfield['terrible'] & defense['excellent'] & bench['excellent'], result['disavantage'])

rule26 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['terrible'] & bench['terrible'], result['extreme_disavantage'])
rule27 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['terrible'] & bench['bad'], result['extreme_disavantage'])
rule28 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['terrible'] & bench['okay'], result['big_disavantage'])
rule29 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['terrible'] & bench['good'], result['big_disavantage'])
rule30 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['terrible'] & bench['excellent'], result['big_disavantage'])
rule31 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['bad'] & bench['terrible'], result['extreme_disavantage'])
rule32 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['bad'] & bench['bad'], result['extreme_disavantage'])
rule33 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['bad'] & bench['okay'], result['big_disavantage'])
rule34 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['bad'] & bench['good'], result['big_disavantage'])
rule35 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['bad'] & bench['excellent'], result['big_disavantage'])
rule36 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['okay'] & bench['terrible'], result['extreme_disavantage'])
rule37 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['okay'] & bench['bad'], result['big_disavantage'])
rule38 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['okay'] & bench['okay'], result['big_disavantage'])
rule39 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['okay'] & bench['good'], result['disavantage'])
rule40 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['okay'] & bench['excellent'], result['disavantage'])
rule41 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['good'] & bench['terrible'], result['big_disavantage'])
rule42 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['good'] & bench['bad'], result['big_disavantage'])
rule43 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['good'] & bench['okay'], result['big_disavantage'])
rule44 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['good'] & bench['good'], result['disavantage'])
rule45 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['good'] & bench['excellent'], result['disavantage'])
rule46 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['excellent'] & bench['terrible'], result['big_disavantage'])
rule47 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['excellent'] & bench['bad'], result['big_disavantage'])
rule48 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['excellent'] & bench['okay'], result['disavantage'])
rule49 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['excellent'] & bench['good'], result['disavantage'])
rule50 = ctrl.Rule(attack['terrible'] & midfield['bad'] & defense['excellent'] & bench['excellent'], result['even'])

rule51 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['terrible'] & bench['terrible'], result['big_disavantage'])
rule52 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['terrible'] & bench['bad'], result['big_disavantage'])
rule53 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['terrible'] & bench['okay'], result['big_disavantage'])
rule54 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['terrible'] & bench['good'], result['big_disavantage'])
rule55 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['terrible'] & bench['excellent'], result['big_disavantage'])
rule56 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['bad'] & bench['terrible'], result['big_disavantage'])
rule57 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['bad'] & bench['bad'], result['big_disavantage'])
rule58 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['bad'] & bench['okay'], result['big_disavantage'])
rule59 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['bad'] & bench['good'], result['big_disavantage'])
rule60 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['bad'] & bench['excellent'], result['disavantage'])
rule61 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['okay'] & bench['terrible'], result['big_disavantage'])
rule62 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['okay'] & bench['bad'], result['big_disavantage'])
rule63 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['okay'] & bench['okay'], result['disavantage'])
rule64 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['okay'] & bench['good'], result['disavantage'])
rule65 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['okay'] & bench['excellent'], result['disavantage'])
rule66 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['good'] & bench['terrible'], result['big_disavantage'])
rule67 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['good'] & bench['bad'], result['big_disavantage'])
rule68 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['good'] & bench['okay'], result['disavantage'])
rule69 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['good'] & bench['good'], result['disavantage'])
rule70 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['good'] & bench['excellent'], result['even'])
rule71 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['excellent'] & bench['terrible'], result['big_disavantage'])
rule72 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['excellent'] & bench['bad'], result['disavantage'])
rule73 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['excellent'] & bench['okay'], result['disavantage'])
rule74 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['excellent'] & bench['good'], result['disavantage'])
rule75 = ctrl.Rule(attack['terrible'] & midfield['okay'] & defense['excellent'] & bench['excellent'], result['even'])

rule76 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['terrible'] & bench['terrible'], result['big_disavantage'])
rule77 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['terrible'] & bench['bad'], result['big_disavantage'])
rule78 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['terrible'] & bench['okay'], result['big_disavantage'])
rule79 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['terrible'] & bench['good'], result['disavantage'])
rule80 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['terrible'] & bench['excellent'], result['disavantage'])
rule81 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['bad'] & bench['terrible'], result['big_disavantage'])
rule82 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['bad'] & bench['bad'], result['big_disavantage'])
rule83 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['bad'] & bench['okay'], result['disavantage'])
rule84 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['bad'] & bench['good'], result['disavantage'])
rule85 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['bad'] & bench['excellent'], result['disavantage'])
rule86 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['okay'] & bench['terrible'], result['big_disavantage'])
rule87 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['okay'] & bench['bad'], result['disavantage'])
rule88 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['okay'] & bench['okay'], result['disavantage'])
rule89 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['okay'] & bench['good'], result['disavantage'])
rule90 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['okay'] & bench['excellent'], result['even'])
rule91 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['good'] & bench['terrible'], result['disavantage'])
rule92 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['good'] & bench['bad'], result['disavantage'])
rule93 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['good'] & bench['okay'], result['even'])
rule94 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['good'] & bench['good'], result['even'])
rule95 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['good'] & bench['excellent'], result['even'])
rule96 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['excellent'] & bench['terrible'], result['disavantage'])
rule97 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['excellent'] & bench['bad'], result['even'])
rule98 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['excellent'] & bench['okay'], result['even'])
rule99 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['excellent'] & bench['good'], result['even'])
rule100 = ctrl.Rule(attack['terrible'] & midfield['good'] & defense['excellent'] & bench['excellent'], result['advantage'])

rule101 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['terrible'] & bench['terrible'], result['disavantage'])
rule102 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['terrible'] & bench['bad'], result['disavantage'])
rule103 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['terrible'] & bench['okay'], result['disavantage'])
rule104 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['terrible'] & bench['good'], result['disavantage'])
rule105 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['terrible'] & bench['excellent'], result['disavantage'])
rule106 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['bad'] & bench['terrible'], result['disavantage'])
rule107 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['bad'] & bench['bad'], result['disavantage'])
rule108 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['bad'] & bench['okay'], result['disavantage'])
rule109 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['bad'] & bench['good'], result['even'])
rule110 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['bad'] & bench['excellent'], result['even'])
rule111 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['okay'] & bench['terrible'], result['disavantage'])
rule112 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['okay'] & bench['bad'], result['disavantage'])
rule113 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['okay'] & bench['okay'], result['even'])
rule114 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['okay'] & bench['good'], result['even'])
rule115 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['okay'] & bench['excellent'], result['even'])
rule116 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['good'] & bench['terrible'], result['even'])
rule117 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['good'] & bench['bad'], result['even'])
rule118 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['good'] & bench['okay'], result['even'])
rule119 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['good'] & bench['good'], result['advantage'])
rule120 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['good'] & bench['excellent'], result['advantage'])
rule121 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['excellent'] & bench['terrible'], result['even'])
rule122 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['excellent'] & bench['bad'], result['even'])
rule123 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['excellent'] & bench['okay'], result['advantage'])
rule124 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['excellent'] & bench['good'], result['advantage'])
rule125 = ctrl.Rule(attack['terrible'] & midfield['excellent'] & defense['excellent'] & bench['excellent'], result['advantage'])


rule126 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['terrible'] & bench['terrible'], result['big_disavantage'])
rule127 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['terrible'] & bench['bad'], result['big_disavantage'])
rule128 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['terrible'] & bench['okay'], result['big_disavantage'])
rule129 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['terrible'] & bench['good'], result['big_disavantage'])
rule130 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['terrible'] & bench['excellent'], result['big_disavantage'])
rule131 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['bad'] & bench['terrible'], result['big_disavantage'])
rule132 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['bad'] & bench['bad'], result['big_disavantage'])
rule133 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['bad'] & bench['okay'], result['big_disavantage'])
rule134 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['bad'] & bench['good'], result['disavantage'])
rule135 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['bad'] & bench['excellent'], result['disavantage'])
rule136 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['okay'] & bench['terrible'], result['big_disavantage'])
rule137 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['okay'] & bench['bad'], result['big_disavantage'])
rule138 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['okay'] & bench['okay'], result['disavantage'])
rule139 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['okay'] & bench['good'], result['disavantage'])
rule140 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['okay'] & bench['excellent'], result['disavantage'])
rule141 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['good'] & bench['terrible'], result['big_disavantage'])
rule142 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['good'] & bench['bad'], result['disavantage'])
rule143 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['good'] & bench['okay'], result['disavantage'])
rule144 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['good'] & bench['good'], result['disavantage'])
rule145 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['good'] & bench['excellent'], result['disavantage'])
rule146 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['excellent'] & bench['terrible'], result['disavantage'])
rule147 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['excellent'] & bench['bad'], result['disavantage'])
rule148 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['excellent'] & bench['okay'], result['even'])
rule149 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['excellent'] & bench['good'], result['even'])
rule150 = ctrl.Rule(attack['bad'] & midfield['terrible'] & defense['excellent'] & bench['excellent'], result['even'])

rule151 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['terrible'] & bench['terrible'], result['big_disavantage'])
rule152 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['terrible'] & bench['bad'], result['big_disavantage'])
rule153 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['terrible'] & bench['okay'], result['big_disavantage'])
rule154 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['terrible'] & bench['good'], result['big_disavantage'])
rule155 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['terrible'] & bench['excellent'], result['big_disavantage'])
rule156 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['bad'] & bench['terrible'], result['big_disavantage'])
rule157 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['bad'] & bench['bad'], result['big_disavantage'])
rule158 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['bad'] & bench['okay'], result['disavantage'])
rule159 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['bad'] & bench['good'], result['disavantage'])
rule160 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['bad'] & bench['excellent'], result['disavantage'])
rule161 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['okay'] & bench['terrible'], result['big_disavantage'])
rule162 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['okay'] & bench['bad'], result['disavantage'])
rule163 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['okay'] & bench['okay'], result['disavantage'])
rule164 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['okay'] & bench['good'], result['disavantage'])
rule165 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['okay'] & bench['excellent'], result['disavantage'])
rule166 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['good'] & bench['terrible'], result['disavantage'])
rule167 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['good'] & bench['bad'], result['disavantage'])
rule168 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['good'] & bench['okay'], result['disavantage'])
rule169 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['good'] & bench['good'], result['disavantage'])
rule170 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['good'] & bench['excellent'], result['even'])
rule171 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['excellent'] & bench['terrible'], result['disavantage'])
rule172 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['excellent'] & bench['bad'], result['disavantage'])
rule173 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['excellent'] & bench['okay'], result['even'])
rule174 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['excellent'] & bench['good'], result['even'])
rule175 = ctrl.Rule(attack['bad'] & midfield['bad'] & defense['excellent'] & bench['excellent'], result['even'])

rule176 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['terrible'] & bench['terrible'], result['big_disavantage'])
rule177 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['terrible'] & bench['bad'], result['big_disavantage'])
rule178 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['terrible'] & bench['okay'], result['big_disavantage'])
rule179 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['terrible'] & bench['good'], result['big_disavantage'])
rule180 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['terrible'] & bench['excellent'], result['disavantage'])
rule181 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['bad'] & bench['terrible'], result['big_disavantage'])
rule182 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['bad'] & bench['bad'], result['big_disavantage'])
rule183 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['bad'] & bench['okay'], result['big_disavantage'])
rule184 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['bad'] & bench['good'], result['disavantage'])
rule185 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['bad'] & bench['excellent'], result['disavantage'])
rule186 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['okay'] & bench['terrible'], result['big_disavantage'])
rule187 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['okay'] & bench['bad'], result['disavantage'])
rule188 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['okay'] & bench['okay'], result['disavantage'])
rule189 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['okay'] & bench['good'], result['disavantage'])
rule190 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['okay'] & bench['excellent'], result['disavantage'])
rule191 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['good'] & bench['terrible'], result['disavantage'])
rule192 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['good'] & bench['bad'], result['even'])
rule193 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['good'] & bench['okay'], result['even'])
rule194 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['good'] & bench['good'], result['even'])
rule195 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['good'] & bench['excellent'], result['even'])
rule196 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['excellent'] & bench['terrible'], result['even'])
rule197 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['excellent'] & bench['bad'], result['even'])
rule198 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['excellent'] & bench['okay'], result['even'])
rule199 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['excellent'] & bench['good'], result['even'])
rule200 = ctrl.Rule(attack['bad'] & midfield['okay'] & defense['excellent'] & bench['excellent'], result['advantage'])

rule201 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['terrible'] & bench['terrible'], result['big_disavantage'])
rule202 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['terrible'] & bench['bad'], result['big_disavantage'])
rule203 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['terrible'] & bench['okay'], result['disavantage'])
rule204 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['terrible'] & bench['good'], result['disavantage'])
rule205 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['terrible'] & bench['excellent'], result['disavantage'])
rule206 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['bad'] & bench['terrible'], result['big_disavantage'])
rule207 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['bad'] & bench['bad'], result['disavantage'])
rule208 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['bad'] & bench['okay'], result['disavantage'])
rule209 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['bad'] & bench['good'], result['disavantage'])
rule210 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['bad'] & bench['excellent'], result['disavantage'])
rule211 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['okay'] & bench['terrible'], result['disavantage'])
rule212 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['okay'] & bench['bad'], result['disavantage'])
rule213 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['okay'] & bench['okay'], result['disavantage'])
rule214 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['okay'] & bench['good'], result['even'])
rule215 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['okay'] & bench['excellent'], result['even'])
rule216 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['good'] & bench['terrible'], result['disavantage'])
rule217 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['good'] & bench['bad'], result['even'])
rule218 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['good'] & bench['okay'], result['even'])
rule219 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['good'] & bench['good'], result['even'])
rule220 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['good'] & bench['excellent'], result['even'])
rule221 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['excellent'] & bench['terrible'], result['even'])
rule222 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['excellent'] & bench['bad'], result['even'])
rule223 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['excellent'] & bench['okay'], result['advantage'])
rule224 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['excellent'] & bench['good'], result['advantage'])
rule225 = ctrl.Rule(attack['bad'] & midfield['good'] & defense['excellent'] & bench['excellent'], result['big_vantage'])

rule226 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['terrible'] & bench['terrible'], result['disavantage'])
rule227 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['terrible'] & bench['bad'], result['disavantage'])
rule228 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['terrible'] & bench['okay'], result['disavantage'])
rule229 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['terrible'] & bench['good'], result['disavantage'])
rule230 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['terrible'] & bench['excellent'], result['disavantage'])
rule231 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['bad'] & bench['terrible'], result['disavantage'])
rule232 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['bad'] & bench['bad'], result['disavantage'])
rule233 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['bad'] & bench['okay'], result['even'])
rule234 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['bad'] & bench['good'], result['even'])
rule235 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['bad'] & bench['excellent'], result['even'])
rule236 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['okay'] & bench['terrible'], result['even'])
rule237 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['okay'] & bench['bad'], result['even'])
rule238 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['okay'] & bench['okay'], result['even'])
rule239 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['okay'] & bench['good'], result['even'])
rule240 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['okay'] & bench['excellent'], result['even'])
rule241 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['good'] & bench['terrible'], result['even'])
rule242 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['good'] & bench['bad'], result['advantage'])
rule243 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['good'] & bench['okay'], result['advantage'])
rule244 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['good'] & bench['good'], result['advantage'])
rule245 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['good'] & bench['excellent'], result['advantage'])
rule246 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['excellent'] & bench['terrible'], result['advantage'])
rule247 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['excellent'] & bench['bad'], result['advantage'])
rule248 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['excellent'] & bench['okay'], result['big_vantage'])
rule249 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['excellent'] & bench['good'], result['big_vantage'])
rule250 = ctrl.Rule(attack['bad'] & midfield['excellent'] & defense['excellent'] & bench['excellent'], result['big_vantage'])


rule251 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['terrible'] & bench['terrible'], result['big_disavantage'])
rule252 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['terrible'] & bench['bad'], result['big_disavantage'])
rule253 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['terrible'] & bench['okay'], result['big_disavantage'])
rule254 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['terrible'] & bench['good'], result['disavantage'])
rule255 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['terrible'] & bench['excellent'], result['disavantage'])
rule256 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['bad'] & bench['terrible'], result['big_disavantage'])
rule257 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['bad'] & bench['bad'], result['disavantage'])
rule258 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['bad'] & bench['okay'], result['disavantage'])
rule259 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['bad'] & bench['good'], result['disavantage'])
rule260 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['bad'] & bench['excellent'], result['disavantage'])
rule261 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['okay'] & bench['terrible'], result['disavantage'])
rule262 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['okay'] & bench['bad'], result['disavantage'])
rule263 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['okay'] & bench['okay'], result['disavantage'])
rule264 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['okay'] & bench['good'], result['disavantage'])
rule265 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['okay'] & bench['excellent'], result['even'])
rule266 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['good'] & bench['terrible'], result['disavantage'])
rule267 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['good'] & bench['bad'], result['disavantage'])
rule268 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['good'] & bench['okay'], result['disavantage'])
rule269 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['good'] & bench['good'], result['even'])
rule270 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['good'] & bench['excellent'], result['even'])
rule271 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['excellent'] & bench['terrible'], result['even'])
rule272 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['excellent'] & bench['bad'], result['even'])
rule273 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['excellent'] & bench['okay'], result['even'])
rule274 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['excellent'] & bench['good'], result['even'])
rule275 = ctrl.Rule(attack['okay'] & midfield['terrible'] & defense['excellent'] & bench['excellent'], result['advantage'])

rule276 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['terrible'] & bench['terrible'], result['disavantage'])
rule277 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['terrible'] & bench['bad'], result['disavantage'])
rule278 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['terrible'] & bench['okay'], result['disavantage'])
rule279 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['terrible'] & bench['good'], result['disavantage'])
rule280 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['terrible'] & bench['excellent'], result['disavantage'])
rule281 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['bad'] & bench['terrible'], result['disavantage'])
rule282 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['bad'] & bench['bad'], result['disavantage'])
rule283 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['bad'] & bench['okay'], result['disavantage'])
rule284 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['bad'] & bench['good'], result['disavantage'])
rule285 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['bad'] & bench['excellent'], result['even'])
rule286 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['okay'] & bench['terrible'], result['disavantage'])
rule287 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['okay'] & bench['bad'], result['disavantage'])
rule288 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['okay'] & bench['okay'], result['disavantage'])
rule289 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['okay'] & bench['good'], result['even'])
rule290 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['okay'] & bench['excellent'], result['even'])
rule291 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['good'] & bench['terrible'], result['even'])
rule292 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['good'] & bench['bad'], result['even'])
rule293 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['good'] & bench['okay'], result['even'])
rule294 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['good'] & bench['good'], result['even'])
rule295 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['good'] & bench['excellent'], result['even'])
rule296 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['excellent'] & bench['terrible'], result['even'])
rule297 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['excellent'] & bench['bad'], result['even'])
rule298 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['excellent'] & bench['okay'], result['even'])
rule299 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['excellent'] & bench['good'], result['advantage'])
rule300 = ctrl.Rule(attack['okay'] & midfield['bad'] & defense['excellent'] & bench['excellent'], result['advantage'])

rule301 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['terrible'] & bench['terrible'], result['disavantage'])
rule302 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['terrible'] & bench['bad'], result['disavantage'])
rule303 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['terrible'] & bench['okay'], result['disavantage'])
rule304 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['terrible'] & bench['good'], result['disavantage'])
rule305 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['terrible'] & bench['excellent'], result['even'])
rule306 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['bad'] & bench['terrible'], result['disavantage'])
rule307 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['bad'] & bench['bad'], result['disavantage'])
rule308 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['bad'] & bench['okay'], result['disavantage'])
rule309 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['bad'] & bench['good'], result['even'])
rule310 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['bad'] & bench['excellent'], result['even'])
rule311 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['okay'] & bench['terrible'], result['disavantage'])
rule312 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['okay'] & bench['bad'], result['even'])
rule313 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['okay'] & bench['okay'], result['even'])
rule314 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['okay'] & bench['good'], result['even'])
rule315 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['okay'] & bench['excellent'], result['even'])
rule316 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['good'] & bench['terrible'], result['even'])
rule317 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['good'] & bench['bad'], result['even'])
rule318 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['good'] & bench['okay'], result['even'])
rule319 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['good'] & bench['good'], result['advantage'])
rule320 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['good'] & bench['excellent'], result['advantage'])
rule321 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['excellent'] & bench['terrible'], result['even'])
rule322 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['excellent'] & bench['bad'], result['advantage'])
rule323 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['excellent'] & bench['okay'], result['advantage'])
rule324 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['excellent'] & bench['good'], result['advantage'])
rule325 = ctrl.Rule(attack['okay'] & midfield['okay'] & defense['excellent'] & bench['excellent'], result['big_vantage'])

rule326 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['terrible'] & bench['terrible'], result['disavantage'])
rule327 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['terrible'] & bench['bad'], result['disavantage'])
rule328 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['terrible'] & bench['okay'], result['disavantage'])
rule329 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['terrible'] & bench['good'], result['even'])
rule330 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['terrible'] & bench['excellent'], result['even'])
rule331 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['bad'] & bench['terrible'], result['disavantage'])
rule332 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['bad'] & bench['bad'], result['disavantage'])
rule333 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['bad'] & bench['okay'], result['even'])
rule334 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['bad'] & bench['good'], result['even'])
rule335 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['bad'] & bench['excellent'], result['even'])
rule336 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['okay'] & bench['terrible'], result['even'])
rule337 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['okay'] & bench['bad'], result['even'])
rule338 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['okay'] & bench['okay'], result['even'])
rule339 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['okay'] & bench['good'], result['even'])
rule340 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['okay'] & bench['excellent'], result['even'])
rule341 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['good'] & bench['terrible'], result['even'])
rule342 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['good'] & bench['bad'], result['even'])
rule343 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['good'] & bench['okay'], result['advantage'])
rule344 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['good'] & bench['good'], result['advantage'])
rule345 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['good'] & bench['excellent'], result['advantage'])
rule346 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['excellent'] & bench['terrible'], result['advantage'])
rule347 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['excellent'] & bench['bad'], result['advantage'])
rule348 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['excellent'] & bench['okay'], result['big_vantage'])
rule349 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['excellent'] & bench['good'], result['big_vantage'])
rule350 = ctrl.Rule(attack['okay'] & midfield['good'] & defense['excellent'] & bench['excellent'], result['big_vantage'])

rule351 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['terrible'] & bench['terrible'], result['disavantage'])
rule352 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['terrible'] & bench['bad'], result['disavantage'])
rule353 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['terrible'] & bench['okay'], result['even'])
rule354 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['terrible'] & bench['good'], result['even'])
rule355 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['terrible'] & bench['excellent'], result['even'])
rule356 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['bad'] & bench['terrible'], result['disavantage'])
rule357 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['bad'] & bench['bad'], result['even'])
rule358 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['bad'] & bench['okay'], result['even'])
rule359 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['bad'] & bench['good'], result['even'])
rule360 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['bad'] & bench['excellent'], result['even'])
rule361 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['okay'] & bench['terrible'], result['even'])
rule362 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['okay'] & bench['bad'], result['even'])
rule363 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['okay'] & bench['okay'], result['even'])
rule364 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['okay'] & bench['good'], result['advantage'])
rule365 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['okay'] & bench['excellent'], result['advantage'])
rule366 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['good'] & bench['terrible'], result['advantage'])
rule367 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['good'] & bench['bad'], result['advantage'])
rule368 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['good'] & bench['okay'], result['advantage'])
rule369 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['good'] & bench['good'], result['big_vantage'])
rule370 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['good'] & bench['excellent'], result['big_vantage'])
rule371 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['excellent'] & bench['terrible'], result['big_vantage'])
rule372 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['excellent'] & bench['bad'], result['big_vantage'])
rule373 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['excellent'] & bench['okay'], result['big_vantage'])
rule374 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['excellent'] & bench['good'], result['big_vantage'])
rule375 = ctrl.Rule(attack['okay'] & midfield['excellent'] & defense['excellent'] & bench['excellent'], result['extreme_vantage'])


rule376 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['terrible'] & bench['terrible'], result['big_disavantage'])
rule377 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['terrible'] & bench['bad'], result['disavantage'])
rule378 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['terrible'] & bench['okay'], result['disavantage'])
rule379 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['terrible'] & bench['good'], result['disavantage'])
rule380 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['terrible'] & bench['excellent'], result['disavantage'])
rule381 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['bad'] & bench['terrible'], result['disavantage'])
rule382 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['bad'] & bench['bad'], result['disavantage'])
rule383 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['bad'] & bench['okay'], result['disavantage'])
rule384 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['bad'] & bench['good'], result['disavantage'])
rule385 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['bad'] & bench['excellent'], result['even'])
rule386 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['okay'] & bench['terrible'], result['disavantage'])
rule387 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['okay'] & bench['bad'], result['disavantage'])
rule388 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['okay'] & bench['okay'], result['even'])
rule389 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['okay'] & bench['good'], result['even'])
rule390 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['okay'] & bench['excellent'], result['even'])
rule391 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['good'] & bench['terrible'], result['even'])
rule392 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['good'] & bench['bad'], result['even'])
rule393 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['good'] & bench['okay'], result['even'])
rule394 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['good'] & bench['good'], result['even'])
rule395 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['good'] & bench['excellent'], result['advantage'])
rule396 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['excellent'] & bench['terrible'], result['even'])
rule397 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['excellent'] & bench['bad'], result['even'])
rule398 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['excellent'] & bench['okay'], result['advantage'])
rule399 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['excellent'] & bench['good'], result['advantage'])
rule400 = ctrl.Rule(attack['good'] & midfield['terrible'] & defense['excellent'] & bench['excellent'], result['advantage'])

rule401 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['terrible'] & bench['terrible'], result['disavantage'])
rule402 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['terrible'] & bench['bad'], result['disavantage'])
rule403 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['terrible'] & bench['okay'], result['disavantage'])
rule404 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['terrible'] & bench['good'], result['disavantage'])
rule405 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['terrible'] & bench['excellent'], result['even'])
rule406 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['bad'] & bench['terrible'], result['disavantage'])
rule407 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['bad'] & bench['bad'], result['disavantage'])
rule408 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['bad'] & bench['okay'], result['disavantage'])
rule409 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['bad'] & bench['good'], result['even'])
rule410 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['bad'] & bench['excellent'], result['even'])
rule411 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['okay'] & bench['terrible'], result['disavantage'])
rule412 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['okay'] & bench['bad'], result['disavantage'])
rule413 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['okay'] & bench['okay'], result['even'])
rule414 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['okay'] & bench['good'], result['even'])
rule415 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['okay'] & bench['excellent'], result['even'])
rule416 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['good'] & bench['terrible'], result['even'])
rule417 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['good'] & bench['bad'], result['even'])
rule418 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['good'] & bench['okay'], result['even'])
rule419 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['good'] & bench['good'], result['advantage'])
rule420 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['good'] & bench['excellent'], result['advantage'])
rule421 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['excellent'] & bench['terrible'], result['even'])
rule422 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['excellent'] & bench['bad'], result['advantage'])
rule423 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['excellent'] & bench['okay'], result['advantage'])
rule424 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['excellent'] & bench['good'], result['advantage'])
rule425 = ctrl.Rule(attack['good'] & midfield['bad'] & defense['excellent'] & bench['excellent'], result['big_vantage'])

rule426 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['terrible'] & bench['terrible'], result['disavantage'])
rule427 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['terrible'] & bench['bad'], result['disavantage'])
rule428 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['terrible'] & bench['okay'], result['disavantage'])
rule429 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['terrible'] & bench['good'], result['even'])
rule430 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['terrible'] & bench['excellent'], result['even'])
rule431 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['bad'] & bench['terrible'], result['disavantage'])
rule432 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['bad'] & bench['bad'], result['disavantage'])
rule433 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['bad'] & bench['okay'], result['even'])
rule434 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['bad'] & bench['good'], result['even'])
rule435 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['bad'] & bench['excellent'], result['even'])
rule436 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['okay'] & bench['terrible'], result['even'])
rule437 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['okay'] & bench['bad'], result['even'])
rule438 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['okay'] & bench['okay'], result['even'])
rule439 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['okay'] & bench['good'], result['advantage'])
rule440 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['okay'] & bench['excellent'], result['advantage'])
rule441 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['good'] & bench['terrible'], result['even'])
rule442 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['good'] & bench['bad'], result['advantage'])
rule443 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['good'] & bench['okay'], result['advantage'])
rule444 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['good'] & bench['good'], result['advantage'])
rule445 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['good'] & bench['excellent'], result['big_vantage'])
rule446 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['excellent'] & bench['terrible'], result['advantage'])
rule447 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['excellent'] & bench['bad'], result['advantage'])
rule448 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['excellent'] & bench['okay'], result['big_vantage'])
rule449 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['excellent'] & bench['good'], result['big_vantage'])
rule450 = ctrl.Rule(attack['good'] & midfield['okay'] & defense['excellent'] & bench['excellent'], result['big_vantage'])

rule451 = ctrl.Rule(attack['good'] & midfield['good'] & defense['terrible'] & bench['terrible'], result['even'])
rule452 = ctrl.Rule(attack['good'] & midfield['good'] & defense['terrible'] & bench['bad'], result['even'])
rule453 = ctrl.Rule(attack['good'] & midfield['good'] & defense['terrible'] & bench['okay'], result['even'])
rule454 = ctrl.Rule(attack['good'] & midfield['good'] & defense['terrible'] & bench['good'], result['even'])
rule455 = ctrl.Rule(attack['good'] & midfield['good'] & defense['terrible'] & bench['excellent'], result['even'])
rule456 = ctrl.Rule(attack['good'] & midfield['good'] & defense['bad'] & bench['terrible'], result['even'])
rule457 = ctrl.Rule(attack['good'] & midfield['good'] & defense['bad'] & bench['bad'], result['even'])
rule458 = ctrl.Rule(attack['good'] & midfield['good'] & defense['bad'] & bench['okay'], result['even'])
rule459 = ctrl.Rule(attack['good'] & midfield['good'] & defense['bad'] & bench['good'], result['even'])
rule460 = ctrl.Rule(attack['good'] & midfield['good'] & defense['bad'] & bench['excellent'], result['advantage'])
rule461 = ctrl.Rule(attack['good'] & midfield['good'] & defense['okay'] & bench['terrible'], result['even'])
rule462 = ctrl.Rule(attack['good'] & midfield['good'] & defense['okay'] & bench['bad'], result['even'])
rule463 = ctrl.Rule(attack['good'] & midfield['good'] & defense['okay'] & bench['okay'], result['advantage'])
rule464 = ctrl.Rule(attack['good'] & midfield['good'] & defense['okay'] & bench['good'], result['advantage'])
rule465 = ctrl.Rule(attack['good'] & midfield['good'] & defense['okay'] & bench['excellent'], result['advantage'])
rule466 = ctrl.Rule(attack['good'] & midfield['good'] & defense['good'] & bench['terrible'], result['advantage'])
rule467 = ctrl.Rule(attack['good'] & midfield['good'] & defense['good'] & bench['bad'], result['advantage'])
rule468 = ctrl.Rule(attack['good'] & midfield['good'] & defense['good'] & bench['okay'], result['advantage'])
rule469 = ctrl.Rule(attack['good'] & midfield['good'] & defense['good'] & bench['good'], result['advantage'])
rule470 = ctrl.Rule(attack['good'] & midfield['good'] & defense['good'] & bench['excellent'], result['big_vantage'])
rule471 = ctrl.Rule(attack['good'] & midfield['good'] & defense['excellent'] & bench['terrible'], result['advantage'])
rule472 = ctrl.Rule(attack['good'] & midfield['good'] & defense['excellent'] & bench['bad'], result['big_vantage'])
rule473 = ctrl.Rule(attack['good'] & midfield['good'] & defense['excellent'] & bench['okay'], result['big_vantage'])
rule474 = ctrl.Rule(attack['good'] & midfield['good'] & defense['excellent'] & bench['good'], result['big_vantage'])
rule475 = ctrl.Rule(attack['good'] & midfield['good'] & defense['excellent'] & bench['excellent'], result['extreme_vantage'])

rule476 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['terrible'] & bench['terrible'], result['even'])
rule477 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['terrible'] & bench['bad'], result['even'])
rule478 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['terrible'] & bench['okay'], result['even'])
rule479 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['terrible'] & bench['good'], result['even'])
rule480 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['terrible'] & bench['excellent'], result['advantage'])
rule481 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['bad'] & bench['terrible'], result['even'])
rule482 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['bad'] & bench['bad'], result['even'])
rule483 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['bad'] & bench['okay'], result['even'])
rule484 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['bad'] & bench['good'], result['advantage'])
rule485 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['bad'] & bench['excellent'], result['advantage'])
rule486 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['okay'] & bench['terrible'], result['even'])
rule487 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['okay'] & bench['bad'], result['advantage'])
rule488 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['okay'] & bench['okay'], result['advantage'])
rule489 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['okay'] & bench['good'], result['advantage'])
rule490 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['okay'] & bench['excellent'], result['advantage'])
rule491 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['good'] & bench['terrible'], result['advantage'])
rule492 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['good'] & bench['bad'], result['big_vantage'])
rule493 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['good'] & bench['okay'], result['big_vantage'])
rule494 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['good'] & bench['good'], result['big_vantage'])
rule495 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['good'] & bench['excellent'], result['big_vantage'])
rule496 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['excellent'] & bench['terrible'], result['big_vantage'])
rule497 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['excellent'] & bench['bad'], result['big_vantage'])
rule498 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['excellent'] & bench['okay'], result['extreme_vantage'])
rule499 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['excellent'] & bench['good'], result['extreme_vantage'])
rule500 = ctrl.Rule(attack['good'] & midfield['excellent'] & defense['excellent'] & bench['excellent'], result['extreme_vantage'])


rule501 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['terrible'] & bench['terrible'], result['disavantage'])
rule502 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['terrible'] & bench['bad'], result['disavantage'])
rule503 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['terrible'] & bench['okay'], result['disavantage'])
rule504 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['terrible'] & bench['good'], result['disavantage'])
rule505 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['terrible'] & bench['excellent'], result['disavantage'])
rule506 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['bad'] & bench['terrible'], result['disavantage'])
rule507 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['bad'] & bench['bad'], result['disavantage'])
rule508 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['bad'] & bench['okay'], result['even'])
rule509 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['bad'] & bench['good'], result['even'])
rule510 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['bad'] & bench['excellent'], result['even'])
rule511 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['okay'] & bench['terrible'], result['even'])
rule512 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['okay'] & bench['bad'], result['even'])
rule513 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['okay'] & bench['okay'], result['even'])
rule514 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['okay'] & bench['good'], result['even'])
rule515 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['okay'] & bench['excellent'], result['even'])
rule516 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['good'] & bench['terrible'], result['even'])
rule517 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['good'] & bench['bad'], result['even'])
rule518 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['good'] & bench['okay'], result['advantage'])
rule519 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['good'] & bench['good'], result['advantage'])
rule520 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['good'] & bench['excellent'], result['advantage'])
rule521 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['excellent'] & bench['terrible'], result['advantage'])
rule522 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['excellent'] & bench['bad'], result['advantage'])
rule523 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['excellent'] & bench['okay'], result['advantage'])
rule524 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['excellent'] & bench['good'], result['big_vantage'])
rule525 = ctrl.Rule(attack['excellent'] & midfield['terrible'] & defense['excellent'] & bench['excellent'], result['big_vantage'])

rule526 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['terrible'] & bench['terrible'], result['disavantage'])
rule527 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['terrible'] & bench['bad'], result['disavantage'])
rule528 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['terrible'] & bench['okay'], result['even'])
rule529 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['terrible'] & bench['good'], result['even'])
rule530 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['terrible'] & bench['excellent'], result['even'])
rule531 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['bad'] & bench['terrible'], result['disavantage'])
rule532 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['bad'] & bench['bad'], result['even'])
rule533 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['bad'] & bench['okay'], result['even'])
rule534 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['bad'] & bench['good'], result['even'])
rule535 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['bad'] & bench['excellent'], result['even'])
rule536 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['okay'] & bench['terrible'], result['even'])
rule537 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['okay'] & bench['bad'], result['even'])
rule538 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['okay'] & bench['okay'], result['even'])
rule539 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['okay'] & bench['good'], result['even'])
rule540 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['okay'] & bench['excellent'], result['advantage'])
rule541 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['good'] & bench['terrible'], result['even'])
rule542 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['good'] & bench['bad'], result['even'])
rule543 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['good'] & bench['okay'], result['advantage'])
rule544 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['good'] & bench['good'], result['advantage'])
rule545 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['good'] & bench['excellent'], result['advantage'])
rule546 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['excellent'] & bench['terrible'], result['advantage'])
rule547 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['excellent'] & bench['bad'], result['advantage'])
rule548 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['excellent'] & bench['okay'], result['big_vantage'])
rule549 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['excellent'] & bench['good'], result['big_vantage'])
rule550 = ctrl.Rule(attack['excellent'] & midfield['bad'] & defense['excellent'] & bench['excellent'], result['big_vantage'])

rule551 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['terrible'] & bench['terrible'], result['disavantage'])
rule552 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['terrible'] & bench['bad'], result['even'])
rule553 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['terrible'] & bench['okay'], result['even'])
rule554 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['terrible'] & bench['good'], result['even'])
rule555 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['terrible'] & bench['excellent'], result['even'])
rule556 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['bad'] & bench['terrible'], result['even'])
rule557 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['bad'] & bench['bad'], result['even'])
rule558 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['bad'] & bench['okay'], result['even'])
rule559 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['bad'] & bench['good'], result['even'])
rule560 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['bad'] & bench['excellent'], result['even'])
rule561 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['okay'] & bench['terrible'], result['even'])
rule562 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['okay'] & bench['bad'], result['advantage'])
rule563 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['okay'] & bench['okay'], result['advantage'])
rule564 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['okay'] & bench['good'], result['advantage'])
rule565 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['okay'] & bench['excellent'], result['big_vantage'])
rule566 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['good'] & bench['terrible'], result['advantage'])
rule567 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['good'] & bench['bad'], result['advantage'])
rule568 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['good'] & bench['okay'], result['big_vantage'])
rule569 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['good'] & bench['good'], result['big_vantage'])
rule570 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['good'] & bench['excellent'], result['big_vantage'])
rule571 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['excellent'] & bench['terrible'], result['big_vantage'])
rule572 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['excellent'] & bench['bad'], result['big_vantage'])
rule573 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['excellent'] & bench['okay'], result['big_vantage'])
rule574 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['excellent'] & bench['good'], result['big_vantage'])
rule575 = ctrl.Rule(attack['excellent'] & midfield['okay'] & defense['excellent'] & bench['excellent'], result['extreme_vantage'])

rule576 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['terrible'] & bench['terrible'], result['even'])
rule577 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['terrible'] & bench['bad'], result['even'])
rule578 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['terrible'] & bench['okay'], result['even'])
rule579 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['terrible'] & bench['good'], result['even'])
rule580 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['terrible'] & bench['excellent'], result['advantage'])
rule581 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['bad'] & bench['terrible'], result['even'])
rule582 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['bad'] & bench['bad'], result['even'])
rule583 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['bad'] & bench['okay'], result['even'])
rule584 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['bad'] & bench['good'], result['advantage'])
rule585 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['bad'] & bench['excellent'], result['advantage'])
rule586 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['okay'] & bench['terrible'], result['advantage'])
rule587 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['okay'] & bench['bad'], result['advantage'])
rule588 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['okay'] & bench['okay'], result['advantage'])
rule589 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['okay'] & bench['good'], result['advantage'])
rule590 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['okay'] & bench['excellent'], result['advantage'])
rule591 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['good'] & bench['terrible'], result['advantage'])
rule592 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['good'] & bench['bad'], result['advantage'])
rule593 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['good'] & bench['okay'], result['big_vantage'])
rule594 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['good'] & bench['good'], result['big_vantage'])
rule595 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['good'] & bench['excellent'], result['big_vantage'])
rule596 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['excellent'] & bench['terrible'], result['big_vantage'])
rule597 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['excellent'] & bench['bad'], result['big_vantage'])
rule598 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['excellent'] & bench['okay'], result['extreme_vantage'])
rule599 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['excellent'] & bench['good'], result['extreme_vantage'])
rule600 = ctrl.Rule(attack['excellent'] & midfield['good'] & defense['excellent'] & bench['excellent'], result['extreme_vantage'])

rule601 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['terrible'] & bench['terrible'], result['even'])
rule602 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['terrible'] & bench['bad'], result['advantage'])
rule603 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['terrible'] & bench['okay'], result['advantage'])
rule604 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['terrible'] & bench['good'], result['advantage'])
rule605 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['terrible'] & bench['excellent'], result['advantage'])
rule606 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['bad'] & bench['terrible'], result['advantage'])
rule607 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['bad'] & bench['bad'], result['advantage'])
rule608 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['bad'] & bench['okay'], result['advantage'])
rule609 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['bad'] & bench['good'], result['advantage'])
rule610 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['bad'] & bench['excellent'], result['big_vantage'])
rule611 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['okay'] & bench['terrible'], result['advantage'])
rule612 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['okay'] & bench['bad'], result['advantage'])
rule613 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['okay'] & bench['okay'], result['big_vantage'])
rule614 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['okay'] & bench['good'], result['big_vantage'])
rule615 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['okay'] & bench['excellent'], result['big_vantage'])
rule616 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['good'] & bench['terrible'], result['big_vantage'])
rule617 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['good'] & bench['bad'], result['big_vantage'])
rule618 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['good'] & bench['okay'], result['big_vantage'])
rule619 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['good'] & bench['good'], result['extreme_vantage'])
rule620 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['good'] & bench['excellent'], result['extreme_vantage'])
rule621 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['excellent'] & bench['terrible'], result['extreme_vantage'])
rule622 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['excellent'] & bench['bad'], result['extreme_vantage'])
rule623 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['excellent'] & bench['okay'], result['extreme_vantage'])
rule624 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['excellent'] & bench['good'], result['extreme_vantage'])
rule625 = ctrl.Rule(attack['excellent'] & midfield['excellent'] & defense['excellent'] & bench['excellent'], result['extreme_vantage'])

wc_ctrl = ctrl.ControlSystem([rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9, rule10, rule11, rule12, rule13, rule14, rule15, rule16, rule17, rule18, rule19,
    rule20, rule21, rule22, rule23, rule24, rule25, rule26, rule27, rule28, rule29, rule30, rule31, rule32, rule33, rule34, rule35, rule36, rule37, rule38, rule39, rule40,
    rule41, rule42, rule43, rule44, rule45, rule46, rule47, rule48, rule49, rule50, rule51, rule52, rule53, rule54, rule55, rule56, rule57, rule58, rule59, rule60, rule61,
    rule62, rule63, rule64, rule65, rule66, rule67, rule68, rule69, rule70, rule71, rule72, rule73, rule74, rule75, rule76, rule77, rule78, rule79, rule80, rule81, rule82,
    rule83, rule84, rule85, rule86, rule87, rule88, rule89, rule90, rule91, rule92, rule93, rule94, rule95, rule96, rule97, rule98, rule99, rule100, rule101, rule102, rule103,
    rule104, rule105, rule106, rule107, rule108, rule109, rule110, rule111, rule112, rule113, rule114, rule115, rule116, rule117, rule118, rule119, rule120, rule121, rule122, rule123,
    rule124, rule125, rule126, rule127, rule128, rule129, rule130, rule131, rule132, rule133, rule134, rule135, rule136, rule137, rule138, rule139, rule140, rule141, rule142, rule143,
    rule144, rule145, rule146, rule147, rule148, rule149, rule150, rule151, rule152, rule153, rule154, rule155, rule156, rule157, rule158, rule159, rule160, rule161, rule162, rule163,
    rule164, rule165, rule166, rule167, rule168, rule169, rule170, rule171, rule172, rule173, rule174, rule175, rule176, rule177, rule178, rule179, rule180, rule181, rule182, rule183,
    rule184, rule185, rule186, rule187, rule188, rule189, rule190, rule191, rule192, rule193, rule194, rule195, rule196, rule197, rule198, rule199, rule200, rule201, rule202, rule203,
    rule204, rule205, rule206, rule207, rule208, rule209, rule210, rule211, rule212, rule213, rule214, rule215, rule216, rule217, rule218, rule219, rule220, rule221, rule222, rule223,
    rule224, rule225, rule226, rule227, rule228, rule229, rule230, rule231, rule232, rule233, rule234, rule235, rule236, rule237, rule238, rule239, rule240, rule241, rule242, rule243,
    rule244, rule245, rule246, rule247, rule248, rule249, rule250, rule251, rule252, rule253, rule254, rule255, rule256, rule257, rule258, rule259, rule260, rule261, rule262, rule263,
    rule264, rule265, rule266, rule267, rule268, rule269, rule270, rule271, rule272, rule273, rule274, rule275, rule276, rule277, rule278, rule279, rule280, rule281, rule282, rule283,
    rule284, rule285, rule286, rule287, rule288, rule289, rule290, rule291, rule292, rule293, rule294, rule295, rule296, rule297, rule298, rule299, rule300, rule301, rule302, rule303,
    rule304, rule305, rule306, rule307, rule308, rule309, rule310, rule311, rule312, rule313, rule314, rule315, rule316, rule317, rule318, rule319, rule320, rule321, rule322, rule323,
    rule324, rule325, rule326, rule327, rule328, rule329, rule330, rule331, rule332, rule333, rule334, rule335, rule336, rule337, rule338, rule339, rule340, rule341, rule342, rule343,
    rule344, rule345, rule346, rule347, rule348, rule349, rule350, rule351, rule352, rule353, rule354, rule355, rule356, rule357, rule358, rule359, rule360, rule361, rule362, rule363,
    rule364, rule365, rule366, rule367, rule368, rule369, rule370, rule371, rule372, rule373, rule374, rule375, rule376, rule377, rule378, rule379, rule380, rule381, rule382, rule383,
    rule384, rule385, rule386, rule387, rule388, rule389, rule390, rule391, rule392, rule393, rule394, rule395, rule396, rule397, rule398, rule399, rule400, rule401, rule402, rule403,
    rule404, rule405, rule406, rule407, rule408, rule409, rule410, rule411, rule412, rule413, rule414, rule415, rule416, rule417, rule418, rule419, rule420, rule421, rule422, rule423,
    rule424, rule425, rule426, rule427, rule428, rule429, rule430, rule431, rule432, rule433, rule434, rule435, rule436, rule437, rule438, rule439, rule440, rule441, rule442, rule443,
    rule444, rule445, rule446, rule447, rule448, rule449, rule450, rule451, rule452, rule453, rule454, rule455, rule456, rule457, rule458, rule459, rule460, rule461, rule462, rule463,
    rule464, rule465, rule466, rule467, rule468, rule469, rule470, rule471, rule472, rule473, rule474, rule475, rule476, rule477, rule478, rule479, rule480, rule481, rule482, rule483,
    rule484, rule485, rule486, rule487, rule488, rule489, rule490, rule491, rule492, rule493, rule494, rule495, rule496, rule497, rule498, rule499, rule500, rule501, rule502, rule503,
    rule504, rule505, rule506, rule507, rule508, rule509, rule510, rule511, rule512, rule513, rule514, rule515, rule516, rule517, rule518, rule519, rule520, rule521, rule522, rule523,
    rule524, rule525, rule526, rule527, rule528, rule529, rule530, rule531, rule532, rule533, rule534, rule535, rule536, rule537, rule538, rule539, rule540, rule541, rule542, rule543,
    rule544, rule545, rule546, rule547, rule548, rule549, rule550, rule551, rule552, rule553, rule554, rule555, rule556, rule557, rule558, rule559, rule560, rule561, rule562, rule563,
    rule564, rule565, rule566, rule567, rule568, rule569, rule570, rule571, rule572, rule573, rule574, rule575, rule576, rule577, rule578, rule579, rule580, rule581, rule582, rule583,
    rule584, rule585, rule586, rule587, rule588, rule589, rule590, rule591, rule592, rule593, rule594, rule595, rule596, rule597, rule598, rule599, rule600, rule601, rule602, rule603,
    rule604, rule605, rule606, rule607, rule608, rule609, rule610, rule611, rule612, rule613, rule614, rule615, rule616, rule617, rule618, rule619, rule620, rule621, rule622, rule623,
    rule624, rule625])

soccer_match = ctrl.ControlSystemSimulation(wc_ctrl)

def entrance_fuzzy(defs, mid, atk, ben):

    soccer_match.input['defense'] = defs
    soccer_match.input['midfield'] = mid
    soccer_match.input['attack'] = atk
    soccer_match.input['bench'] = ben

    soccer_match.compute()

    # print (soccer_match.output['result'])
    # result.view(sim=soccer_match)
    # plt.show()

    return soccer_match.output['result']
